Repository hassio-addons/addon-uptime-kuma, pull requests merged in 2023-03, with the labels that each got.

#54 ⬆️ Upgrades add-on base image to 13.1.3
  uptime-kuma/Dockerfile
  uptime-kuma/build.yaml
Labels: dependencies

#55 ⬆️ Upgrades Uptime Kuma to 1.20.1
  uptime-kuma/Dockerfile
Labels: dependencies, minor

#62 Add Renovate for dependency management
  .github/dependabot.yaml
  .github/renovate.json
  uptime-kuma/Dockerfile
Labels: maintenance

#67 Fix broken URL
  uptime-kuma/DOCS.md
Labels: documentation
